import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { ArrowLeft, Save, Plus, Trash2, Sparkles } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { useToastStore } from '../../stores';
import { Button, Input, Card, Select } from '../ui';

interface VariantInput {
  size: string;
  color: string;
  color_code: string;
  inventory_quantity: number;
}

export default function AdminNewProduct() {
  const navigate = useNavigate();
  const { addToast } = useToastStore();
  const [loading, setLoading] = useState(false);

  // Form State
  const [name, setName] = useState('');
  const [sku, setSku] = useState('');
  const [slug, setSlug] = useState('');
  const [category, setCategory] = useState<'men' | 'women' | 'unisex' | 'kids'>('unisex');
  const [subcategory, setSubcategory] = useState<'tops' | 'bottoms' | 'dresses' | 'outerwear' | 'accessories' | 'footwear' | 'activewear' | 'ethnic' | 'loungewear'>('tops');
  const [season, setSeason] = useState<'summer' | 'monsoon' | 'autumn' | 'winter' | 'festive'>('summer');
  const [basePrice, setBasePrice] = useState('');
  const [salePrice, setSalePrice] = useState('');
  const [description, setDescription] = useState('');
  const [imageUrl, setImageUrl] = useState('');

  // Variants State
  const [variants, setVariants] = useState<VariantInput[]>([
    { size: 'S', color: 'Black', color_code: '#000000', inventory_quantity: 10 },
    { size: 'M', color: 'Black', color_code: '#000000', inventory_quantity: 20 },
    { size: 'L', color: 'Black', color_code: '#000000', inventory_quantity: 15 },
  ]);

  const autoGenerateDetails = () => {
    if (!name.trim()) {
      addToast({
        type: 'error',
        title: 'Missing name',
        message: 'Please enter a product name first.',
      });
      return;
    }

    // Generate Slug
    const generatedSlug = name
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, '')
      .replace(/[\s_-]+/g, '-')
      .replace(/^-+|-+$/g, '');
    setSlug(generatedSlug);

    // Generate SKU
    const prefix = category.substring(0, 3).toUpperCase();
    const randomNum = Math.floor(1000 + Math.random() * 9000);
    setSku(`${prefix}-${randomNum}`);
  };

  const handleAddVariant = () => {
    setVariants((prev) => [
      ...prev,
      { size: 'M', color: 'Default', color_code: '#000000', inventory_quantity: 10 },
    ]);
  };

  const handleRemoveVariant = (index: number) => {
    if (variants.length <= 1) {
      addToast({
        type: 'error',
        title: 'Min variants',
        message: 'A product must have at least one variant.',
      });
      return;
    }
    setVariants((prev) => prev.filter((_, i) => i !== index));
  };

  const handleVariantChange = (index: number, field: keyof VariantInput, value: any) => {
    setVariants((prev) =>
      prev.map((v, i) => (i === index ? { ...v, [field]: value } : v))
    );
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!name.trim() || !sku.trim() || !slug.trim() || !basePrice || !description.trim()) {
      addToast({
        type: 'error',
        title: 'Validation failed',
        message: 'Please fill in all required fields.',
      });
      return;
    }

    setLoading(true);

    try {
      // 1. Insert product row
      const { data: productData, error: productError } = await supabase
        .from('products')
        .insert([
          {
            name,
            sku,
            slug,
            category,
            subcategory,
            season,
            base_price: Number(basePrice),
            sale_price: salePrice ? Number(salePrice) : null,
            description,
          },
        ])
        .select()
        .single();

      if (productError) throw productError;
      const productId = productData.id;

      // 2. Insert primary product image
      const primaryImage = imageUrl.trim() || 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=60';
      const { error: imageError } = await supabase
        .from('product_images')
        .insert([
          {
            product_id: productId,
            url: primaryImage,
            alt: name,
            is_primary: true,
            sort_order: 0,
          },
        ]);

      if (imageError) throw imageError;

      // 3. Insert product variants
      const formattedVariants = variants.map((v) => ({
        product_id: productId,
        size: v.size,
        color: v.color,
        color_code: v.color_code,
        sku: `${sku}-${v.color.substring(0, 2).toUpperCase()}-${v.size}`,
        inventory_quantity: Number(v.inventory_quantity) || 0,
        is_in_stock: (Number(v.inventory_quantity) || 0) > 0,
      }));

      const { error: variantsError } = await supabase
        .from('product_variants')
        .insert(formattedVariants);

      if (variantsError) throw variantsError;

      addToast({
        type: 'success',
        title: 'Product created',
        message: 'Successfully added new product to the catalog.',
      });

      navigate('/admin/products');
    } catch (err: any) {
      console.error('Error inserting product:', err);
      addToast({
        type: 'error',
        title: 'Save failed',
        message: err.message || 'Check database constraints or inputs.',
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 max-w-5xl">
      <div className="flex items-center gap-3">
        <Link to="/admin/products" className="p-2 hover:bg-neutral-100 dark:hover:bg-neutral-800 rounded-lg text-neutral-600 dark:text-neutral-400">
          <ArrowLeft className="w-5 h-5" />
        </Link>
        <div>
          <h1 className="text-2xl font-bold text-neutral-900 dark:text-white">Add New Product</h1>
          <p className="text-neutral-500 mt-1">Insert a new item, images, and sizing variants into the catalog.</p>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          {/* General Information Card */}
          <Card className="p-6 space-y-4">
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white">Product Information</h2>
            <Input
              label="Product Name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. Premium Linen Shirt"
              required
            />

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="relative">
                <Input
                  label="SKU"
                  value={sku}
                  onChange={(e) => setSku(e.target.value)}
                  placeholder="e.g. TS-1004"
                  required
                />
                <button
                  type="button"
                  onClick={autoGenerateDetails}
                  className="absolute right-2 top-8 text-primary-600 hover:text-primary-700 p-1.5"
                  title="Auto Generate SKU & Slug"
                >
                  <Sparkles className="w-4 h-4" />
                </button>
              </div>
              <Input
                label="Slug URL"
                value={slug}
                onChange={(e) => setSlug(e.target.value)}
                placeholder="e.g. premium-linen-shirt"
                required
              />
            </div>

            <div>
              <label className="label">Full Product Description</label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className="input min-h-[120px] resize-y"
                placeholder="Write a descriptive marketing copy..."
                required
              />
            </div>
          </Card>

          {/* Pricing & Stock Card */}
          <Card className="p-6 space-y-4">
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white">Pricing & Logistics</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <Input
                label="Base Price (₹)"
                type="number"
                value={basePrice}
                onChange={(e) => setBasePrice(e.target.value)}
                placeholder="e.g. 1499"
                required
              />
              <Input
                label="Sale Price (₹, optional)"
                type="number"
                value={salePrice}
                onChange={(e) => setSalePrice(e.target.value)}
                placeholder="e.g. 1199"
              />
            </div>
            <Input
              label="Primary Image URL"
              value={imageUrl}
              onChange={(e) => setImageUrl(e.target.value)}
              placeholder="https://images.unsplash.com/..."
            />
          </Card>

          {/* Sizing & Stock Variants Card */}
          <Card className="p-6 space-y-4">
            <div className="flex justify-between items-center pb-2 border-b border-neutral-100 dark:border-neutral-800">
              <h2 className="text-lg font-semibold text-neutral-900 dark:text-white">Sizing & Color Variants</h2>
              <Button type="button" variant="outline" size="sm" onClick={handleAddVariant} className="flex items-center gap-1.5">
                <Plus className="w-4 h-4" /> Add Variant
              </Button>
            </div>

            <div className="space-y-4">
              {variants.map((v, index) => (
                <div key={index} className="flex flex-wrap items-end gap-3 p-3 bg-neutral-50 dark:bg-neutral-800/40 rounded-xl">
                  <div className="w-16">
                    <Input
                      label="Size"
                      value={v.size}
                      onChange={(e) => handleVariantChange(index, 'size', e.target.value)}
                      placeholder="S"
                      required
                    />
                  </div>
                  <div className="flex-1 min-w-[100px]">
                    <Input
                      label="Color"
                      value={v.color}
                      onChange={(e) => handleVariantChange(index, 'color', e.target.value)}
                      placeholder="Black"
                      required
                    />
                  </div>
                  <div className="w-24">
                    <Input
                      label="Hex Code"
                      type="color"
                      value={v.color_code}
                      onChange={(e) => handleVariantChange(index, 'color_code', e.target.value)}
                      required
                    />
                  </div>
                  <div className="w-24">
                    <Input
                      label="Stock"
                      type="number"
                      value={v.inventory_quantity}
                      onChange={(e) => handleVariantChange(index, 'inventory_quantity', Number(e.target.value))}
                      required
                    />
                  </div>
                  <button
                    type="button"
                    onClick={() => handleRemoveVariant(index)}
                    className="p-2 mb-1 hover:bg-error-50 rounded text-error-600 transition-colors"
                  >
                    <Trash2 className="w-5 h-5" />
                  </button>
                </div>
              ))}
            </div>
          </Card>
        </div>

        {/* Categories & Collections Sidebar Card */}
        <div className="space-y-6">
          <Card className="p-6 space-y-4">
            <h2 className="text-lg font-semibold text-neutral-900 dark:text-white">Taxonomy</h2>

            <Select
              label="Target Gender/Category"
              value={category}
              onChange={(e) => setCategory(e.target.value as any)}
              options={[
                { value: 'men', label: 'Men' },
                { value: 'women', label: 'Women' },
                { value: 'unisex', label: 'Unisex' },
                { value: 'kids', label: 'Kids' },
              ]}
              required
            />

            <Select
              label="Product Subcategory"
              value={subcategory}
              onChange={(e) => setSubcategory(e.target.value as any)}
              options={[
                { value: 'tops', label: 'Tops' },
                { value: 'bottoms', label: 'Bottoms' },
                { value: 'dresses', label: 'Dresses' },
                { value: 'outerwear', label: 'Outerwear' },
                { value: 'accessories', label: 'Accessories' },
                { value: 'footwear', label: 'Footwear' },
                { value: 'activewear', label: 'Activewear' },
                { value: 'ethnic', label: 'Ethnic' },
                { value: 'loungewear', label: 'Loungewear' },
              ]}
              required
            />

            <Select
              label="Season Theme"
              value={season}
              onChange={(e) => setSeason(e.target.value as any)}
              options={[
                { value: 'summer', label: 'Summer' },
                { value: 'monsoon', label: 'Monsoon' },
                { value: 'autumn', label: 'Autumn' },
                { value: 'winter', label: 'Winter' },
                { value: 'festive', label: 'Festive' },
              ]}
              required
            />
          </Card>

          <Card className="p-6">
            <Button type="submit" variant="primary" className="w-full flex items-center justify-center gap-2" isLoading={loading}>
              <Save className="w-5 h-5" /> Save Product
            </Button>
          </Card>
        </div>
      </form>
    </div>
  );
}
